// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"job-tracker/internal/domain/entity"
	"job-tracker/internal/domain/repository"
	"job-tracker/internal/domain/valueobject"

	mock "github.com/stretchr/testify/mock"
)

// NewMockApplicationRepository creates a new instance of MockApplicationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplicationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplicationRepository {
	mock := &MockApplicationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplicationRepository is an autogenerated mock type for the ApplicationRepository type
type MockApplicationRepository struct {
	mock.Mock
}

type MockApplicationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplicationRepository) EXPECT() *MockApplicationRepository_Expecter {
	return &MockApplicationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockApplicationRepository
func (_mock *MockApplicationRepository) Create(ctx context.Context, app *entity.Application) (*entity.Application, error) {
	ret := _mock.Called(ctx, app)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Application
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Application) (*entity.Application, error)); ok {
		return returnFunc(ctx, app)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Application) *entity.Application); ok {
		r0 = returnFunc(ctx, app)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Application)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Application) error); ok {
		r1 = returnFunc(ctx, app)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApplicationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockApplicationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - app *entity.Application
func (_e *MockApplicationRepository_Expecter) Create(ctx interface{}, app interface{}) *MockApplicationRepository_Create_Call {
	return &MockApplicationRepository_Create_Call{Call: _e.mock.On("Create", ctx, app)}
}

func (_c *MockApplicationRepository_Create_Call) Run(run func(ctx context.Context, app *entity.Application)) *MockApplicationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Application
		if args[1] != nil {
			arg1 = args[1].(*entity.Application)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApplicationRepository_Create_Call) Return(application *entity.Application, err error) *MockApplicationRepository_Create_Call {
	_c.Call.Return(application, err)
	return _c
}

func (_c *MockApplicationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, app *entity.Application) (*entity.Application, error)) *MockApplicationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockApplicationRepository
func (_mock *MockApplicationRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplicationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockApplicationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockApplicationRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockApplicationRepository_Delete_Call {
	return &MockApplicationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockApplicationRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockApplicationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApplicationRepository_Delete_Call) Return(err error) *MockApplicationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplicationRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockApplicationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockApplicationRepository
func (_mock *MockApplicationRepository) FindByID(ctx context.Context, id int64) (*entity.Application, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Application
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.Application, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.Application); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Application)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApplicationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockApplicationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockApplicationRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockApplicationRepository_FindByID_Call {
	return &MockApplicationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockApplicationRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockApplicationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApplicationRepository_FindByID_Call) Return(application *entity.Application, err error) *MockApplicationRepository_FindByID_Call {
	_c.Call.Return(application, err)
	return _c
}

func (_c *MockApplicationRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*entity.Application, error)) *MockApplicationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockApplicationRepository
func (_mock *MockApplicationRepository) List(ctx context.Context, userID int64, filters repository.ListFilters, page valueobject.PageRequest) ([]entity.Application, int64, error) {
	ret := _mock.Called(ctx, userID, filters, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Application
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, repository.ListFilters, valueobject.PageRequest) ([]entity.Application, int64, error)); ok {
		return returnFunc(ctx, userID, filters, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, repository.ListFilters, valueobject.PageRequest) []entity.Application); ok {
		r0 = returnFunc(ctx, userID, filters, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Application)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, repository.ListFilters, valueobject.PageRequest) int64); ok {
		r1 = returnFunc(ctx, userID, filters, page)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, repository.ListFilters, valueobject.PageRequest) error); ok {
		r2 = returnFunc(ctx, userID, filters, page)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockApplicationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockApplicationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - filters repository.ListFilters
//   - page valueobject.PageRequest
func (_e *MockApplicationRepository_Expecter) List(ctx interface{}, userID interface{}, filters interface{}, page interface{}) *MockApplicationRepository_List_Call {
	return &MockApplicationRepository_List_Call{Call: _e.mock.On("List", ctx, userID, filters, page)}
}

func (_c *MockApplicationRepository_List_Call) Run(run func(ctx context.Context, userID int64, filters repository.ListFilters, page valueobject.PageRequest)) *MockApplicationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 repository.ListFilters
		if args[2] != nil {
			arg2 = args[2].(repository.ListFilters)
		}
		var arg3 valueobject.PageRequest
		if args[3] != nil {
			arg3 = args[3].(valueobject.PageRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockApplicationRepository_List_Call) Return(applications []entity.Application, n int64, err error) *MockApplicationRepository_List_Call {
	_c.Call.Return(applications, n, err)
	return _c
}

func (_c *MockApplicationRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID int64, filters repository.ListFilters, page valueobject.PageRequest) ([]entity.Application, int64, error)) *MockApplicationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithHistory provides a mock function for the type MockApplicationRepository
func (_mock *MockApplicationRepository) UpdateWithHistory(ctx context.Context, app *entity.Application, note string) error {
	ret := _mock.Called(ctx, app, note)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithHistory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Application, string) error); ok {
		r0 = returnFunc(ctx, app, note)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplicationRepository_UpdateWithHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithHistory'
type MockApplicationRepository_UpdateWithHistory_Call struct {
	*mock.Call
}

// UpdateWithHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - app *entity.Application
//   - note string
func (_e *MockApplicationRepository_Expecter) UpdateWithHistory(ctx interface{}, app interface{}, note interface{}) *MockApplicationRepository_UpdateWithHistory_Call {
	return &MockApplicationRepository_UpdateWithHistory_Call{Call: _e.mock.On("UpdateWithHistory", ctx, app, note)}
}

func (_c *MockApplicationRepository_UpdateWithHistory_Call) Run(run func(ctx context.Context, app *entity.Application, note string)) *MockApplicationRepository_UpdateWithHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Application
		if args[1] != nil {
			arg1 = args[1].(*entity.Application)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockApplicationRepository_UpdateWithHistory_Call) Return(err error) *MockApplicationRepository_UpdateWithHistory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplicationRepository_UpdateWithHistory_Call) RunAndReturn(run func(ctx context.Context, app *entity.Application, note string) error) *MockApplicationRepository_UpdateWithHistory_Call {
	_c.Call.Return(run)
	return _c
}
