// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"job-tracker/internal/domain/entity"
	"job-tracker/internal/domain/repository"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDashboardRepository creates a new instance of MockDashboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDashboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDashboardRepository {
	mock := &MockDashboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDashboardRepository is an autogenerated mock type for the DashboardRepository type
type MockDashboardRepository struct {
	mock.Mock
}

type MockDashboardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDashboardRepository) EXPECT() *MockDashboardRepository_Expecter {
	return &MockDashboardRepository_Expecter{mock: &_m.Mock}
}

// CountByStatus provides a mock function for the type MockDashboardRepository
func (_mock *MockDashboardRepository) CountByStatus(ctx context.Context, userID int64) ([]repository.StatusCount, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 []repository.StatusCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]repository.StatusCount, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []repository.StatusCount); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.StatusCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDashboardRepository_CountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatus'
type MockDashboardRepository_CountByStatus_Call struct {
	*mock.Call
}

// CountByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockDashboardRepository_Expecter) CountByStatus(ctx interface{}, userID interface{}) *MockDashboardRepository_CountByStatus_Call {
	return &MockDashboardRepository_CountByStatus_Call{Call: _e.mock.On("CountByStatus", ctx, userID)}
}

func (_c *MockDashboardRepository_CountByStatus_Call) Run(run func(ctx context.Context, userID int64)) *MockDashboardRepository_CountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDashboardRepository_CountByStatus_Call) Return(statusCounts []repository.StatusCount, err error) *MockDashboardRepository_CountByStatus_Call {
	_c.Call.Return(statusCounts, err)
	return _c
}

func (_c *MockDashboardRepository_CountByStatus_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]repository.StatusCount, error)) *MockDashboardRepository_CountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CountCreatedBetween provides a mock function for the type MockDashboardRepository
func (_mock *MockDashboardRepository) CountCreatedBetween(ctx context.Context, userID int64, from time.Time, to time.Time) ([]repository.StatusCount, error) {
	ret := _mock.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CountCreatedBetween")
	}

	var r0 []repository.StatusCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) ([]repository.StatusCount, error)); ok {
		return returnFunc(ctx, userID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) []repository.StatusCount); ok {
		r0 = returnFunc(ctx, userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.StatusCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDashboardRepository_CountCreatedBetween_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCreatedBetween'
type MockDashboardRepository_CountCreatedBetween_Call struct {
	*mock.Call
}

// CountCreatedBetween is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - from time.Time
//   - to time.Time
func (_e *MockDashboardRepository_Expecter) CountCreatedBetween(ctx interface{}, userID interface{}, from interface{}, to interface{}) *MockDashboardRepository_CountCreatedBetween_Call {
	return &MockDashboardRepository_CountCreatedBetween_Call{Call: _e.mock.On("CountCreatedBetween", ctx, userID, from, to)}
}

func (_c *MockDashboardRepository_CountCreatedBetween_Call) Run(run func(ctx context.Context, userID int64, from time.Time, to time.Time)) *MockDashboardRepository_CountCreatedBetween_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDashboardRepository_CountCreatedBetween_Call) Return(statusCounts []repository.StatusCount, err error) *MockDashboardRepository_CountCreatedBetween_Call {
	_c.Call.Return(statusCounts, err)
	return _c
}

func (_c *MockDashboardRepository_CountCreatedBetween_Call) RunAndReturn(run func(ctx context.Context, userID int64, from time.Time, to time.Time) ([]repository.StatusCount, error)) *MockDashboardRepository_CountCreatedBetween_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecent provides a mock function for the type MockDashboardRepository
func (_mock *MockDashboardRepository) ListRecent(ctx context.Context, userID int64, limit int) ([]entity.Application, error) {
	ret := _mock.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRecent")
	}

	var r0 []entity.Application
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) ([]entity.Application, error)); ok {
		return returnFunc(ctx, userID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) []entity.Application); ok {
		r0 = returnFunc(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Application)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = returnFunc(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDashboardRepository_ListRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecent'
type MockDashboardRepository_ListRecent_Call struct {
	*mock.Call
}

// ListRecent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - limit int
func (_e *MockDashboardRepository_Expecter) ListRecent(ctx interface{}, userID interface{}, limit interface{}) *MockDashboardRepository_ListRecent_Call {
	return &MockDashboardRepository_ListRecent_Call{Call: _e.mock.On("ListRecent", ctx, userID, limit)}
}

func (_c *MockDashboardRepository_ListRecent_Call) Run(run func(ctx context.Context, userID int64, limit int)) *MockDashboardRepository_ListRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDashboardRepository_ListRecent_Call) Return(applications []entity.Application, err error) *MockDashboardRepository_ListRecent_Call {
	_c.Call.Return(applications, err)
	return _c
}

func (_c *MockDashboardRepository_ListRecent_Call) RunAndReturn(run func(ctx context.Context, userID int64, limit int) ([]entity.Application, error)) *MockDashboardRepository_ListRecent_Call {
	_c.Call.Return(run)
	return _c
}
