// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"job-tracker/internal/domain/repository"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalyticsRepository creates a new instance of MockAnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type MockAnalyticsRepository struct {
	mock.Mock
}

type MockAnalyticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepository_Expecter {
	return &MockAnalyticsRepository_Expecter{mock: &_m.Mock}
}

// CountByStatus provides a mock function for the type MockAnalyticsRepository
func (_mock *MockAnalyticsRepository) CountByStatus(ctx context.Context, userID int64) ([]repository.StatusCount, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 []repository.StatusCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]repository.StatusCount, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []repository.StatusCount); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.StatusCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsRepository_CountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatus'
type MockAnalyticsRepository_CountByStatus_Call struct {
	*mock.Call
}

// CountByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAnalyticsRepository_Expecter) CountByStatus(ctx interface{}, userID interface{}) *MockAnalyticsRepository_CountByStatus_Call {
	return &MockAnalyticsRepository_CountByStatus_Call{Call: _e.mock.On("CountByStatus", ctx, userID)}
}

func (_c *MockAnalyticsRepository_CountByStatus_Call) Run(run func(ctx context.Context, userID int64)) *MockAnalyticsRepository_CountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsRepository_CountByStatus_Call) Return(statusCounts []repository.StatusCount, err error) *MockAnalyticsRepository_CountByStatus_Call {
	_c.Call.Return(statusCounts, err)
	return _c
}

func (_c *MockAnalyticsRepository_CountByStatus_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]repository.StatusCount, error)) *MockAnalyticsRepository_CountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvgResponseDays provides a mock function for the type MockAnalyticsRepository
func (_mock *MockAnalyticsRepository) GetAvgResponseDays(ctx context.Context, userID int64) (float64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvgResponseDays")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (float64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) float64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsRepository_GetAvgResponseDays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvgResponseDays'
type MockAnalyticsRepository_GetAvgResponseDays_Call struct {
	*mock.Call
}

// GetAvgResponseDays is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAnalyticsRepository_Expecter) GetAvgResponseDays(ctx interface{}, userID interface{}) *MockAnalyticsRepository_GetAvgResponseDays_Call {
	return &MockAnalyticsRepository_GetAvgResponseDays_Call{Call: _e.mock.On("GetAvgResponseDays", ctx, userID)}
}

func (_c *MockAnalyticsRepository_GetAvgResponseDays_Call) Run(run func(ctx context.Context, userID int64)) *MockAnalyticsRepository_GetAvgResponseDays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsRepository_GetAvgResponseDays_Call) Return(f float64, err error) *MockAnalyticsRepository_GetAvgResponseDays_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockAnalyticsRepository_GetAvgResponseDays_Call) RunAndReturn(run func(ctx context.Context, userID int64) (float64, error)) *MockAnalyticsRepository_GetAvgResponseDays_Call {
	_c.Call.Return(run)
	return _c
}

// GetSourceBreakdown provides a mock function for the type MockAnalyticsRepository
func (_mock *MockAnalyticsRepository) GetSourceBreakdown(ctx context.Context, userID int64) ([]repository.SourceBreakdownRow, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSourceBreakdown")
	}

	var r0 []repository.SourceBreakdownRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]repository.SourceBreakdownRow, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []repository.SourceBreakdownRow); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.SourceBreakdownRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsRepository_GetSourceBreakdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSourceBreakdown'
type MockAnalyticsRepository_GetSourceBreakdown_Call struct {
	*mock.Call
}

// GetSourceBreakdown is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAnalyticsRepository_Expecter) GetSourceBreakdown(ctx interface{}, userID interface{}) *MockAnalyticsRepository_GetSourceBreakdown_Call {
	return &MockAnalyticsRepository_GetSourceBreakdown_Call{Call: _e.mock.On("GetSourceBreakdown", ctx, userID)}
}

func (_c *MockAnalyticsRepository_GetSourceBreakdown_Call) Run(run func(ctx context.Context, userID int64)) *MockAnalyticsRepository_GetSourceBreakdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsRepository_GetSourceBreakdown_Call) Return(sourceBreakdownRows []repository.SourceBreakdownRow, err error) *MockAnalyticsRepository_GetSourceBreakdown_Call {
	_c.Call.Return(sourceBreakdownRows, err)
	return _c
}

func (_c *MockAnalyticsRepository_GetSourceBreakdown_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]repository.SourceBreakdownRow, error)) *MockAnalyticsRepository_GetSourceBreakdown_Call {
	_c.Call.Return(run)
	return _c
}

// GetWeeklyApplications provides a mock function for the type MockAnalyticsRepository
func (_mock *MockAnalyticsRepository) GetWeeklyApplications(ctx context.Context, userID int64, from time.Time, numWeeks int) ([]repository.WeeklyAppRow, error) {
	ret := _mock.Called(ctx, userID, from, numWeeks)

	if len(ret) == 0 {
		panic("no return value specified for GetWeeklyApplications")
	}

	var r0 []repository.WeeklyAppRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, int) ([]repository.WeeklyAppRow, error)); ok {
		return returnFunc(ctx, userID, from, numWeeks)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, int) []repository.WeeklyAppRow); ok {
		r0 = returnFunc(ctx, userID, from, numWeeks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.WeeklyAppRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time, int) error); ok {
		r1 = returnFunc(ctx, userID, from, numWeeks)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsRepository_GetWeeklyApplications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWeeklyApplications'
type MockAnalyticsRepository_GetWeeklyApplications_Call struct {
	*mock.Call
}

// GetWeeklyApplications is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - from time.Time
//   - numWeeks int
func (_e *MockAnalyticsRepository_Expecter) GetWeeklyApplications(ctx interface{}, userID interface{}, from interface{}, numWeeks interface{}) *MockAnalyticsRepository_GetWeeklyApplications_Call {
	return &MockAnalyticsRepository_GetWeeklyApplications_Call{Call: _e.mock.On("GetWeeklyApplications", ctx, userID, from, numWeeks)}
}

func (_c *MockAnalyticsRepository_GetWeeklyApplications_Call) Run(run func(ctx context.Context, userID int64, from time.Time, numWeeks int)) *MockAnalyticsRepository_GetWeeklyApplications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAnalyticsRepository_GetWeeklyApplications_Call) Return(weeklyAppRows []repository.WeeklyAppRow, err error) *MockAnalyticsRepository_GetWeeklyApplications_Call {
	_c.Call.Return(weeklyAppRows, err)
	return _c
}

func (_c *MockAnalyticsRepository_GetWeeklyApplications_Call) RunAndReturn(run func(ctx context.Context, userID int64, from time.Time, numWeeks int) ([]repository.WeeklyAppRow, error)) *MockAnalyticsRepository_GetWeeklyApplications_Call {
	_c.Call.Return(run)
	return _c
}
