// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Generate(userID int64, email string) (string, error) {
	ret := _mock.Called(userID, email)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) (string, error)); ok {
		return returnFunc(userID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, string) string); ok {
		r0 = returnFunc(userID, email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = returnFunc(userID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockTokenService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID int64
//   - email string
func (_e *MockTokenService_Expecter) Generate(userID interface{}, email interface{}) *MockTokenService_Generate_Call {
	return &MockTokenService_Generate_Call{Call: _e.mock.On("Generate", userID, email)}
}

func (_c *MockTokenService_Generate_Call) Run(run func(userID int64, email string)) *MockTokenService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_Generate_Call) Return(s string, err error) *MockTokenService_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenService_Generate_Call) RunAndReturn(run func(userID int64, email string) (string, error)) *MockTokenService_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Validate(token string) (int64, string, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 int64
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, string, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) string); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) Validate(token interface{}) *MockTokenService_Validate_Call {
	return &MockTokenService_Validate_Call{Call: _e.mock.On("Validate", token)}
}

func (_c *MockTokenService_Validate_Call) Run(run func(token string)) *MockTokenService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_Validate_Call) Return(userID int64, email string, err error) *MockTokenService_Validate_Call {
	_c.Call.Return(userID, email, err)
	return _c
}

func (_c *MockTokenService_Validate_Call) RunAndReturn(run func(token string) (int64, string, error)) *MockTokenService_Validate_Call {
	_c.Call.Return(run)
	return _c
}
