basePath: /api/v1
definitions:
  internal_infrastructure_http_handler.successResponse:
    properties:
      data: {}
      success:
        type: boolean
    type: object
host: localhost:3001
info:
  contact: {}
  description: Single-user job application tracker API.
  title: Job Tracker API
  version: 1.0.0
paths:
  /health:
    get:
      description: Returns API health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_infrastructure_http_handler.successResponse'
      summary: Health check
      tags:
      - health
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
